### ISSUE TITLE
Make a main menu on the GUI that links to instuctions page, highscores, new game

### ISSUE THREAD

**Issue by juliomaldonado** [UCSB-CS56-Projects/cs56-games-memory-card#22]
The current design has a new game launch initially with the instructions page as an additional window. If this window is closed, the user must relaunch the game if they want to read the instructions again since currently it is gone forever when closed. The high scores page is also on the sidebar while the game is running, it should be on a centralized start menu instead.

**Comment by juliomaldonado** [comment]
The current design has a new game launch initially with the instructions page as an additional window. The user must relaunch the game if they want to read the instructions again. The high scores page is also on the sidebar while the game is running, it should be on a centralized start menu instead.

**Comment by dcoffill** [comment]
Approved
Estimated ~350 points
