### ISSUE TITLE
Occasional High Score Value Bug (Additional recommendation for next generation of coders)

### ISSUE THREAD

**Issue by juliomaldonado** [UCSB-CS56-Projects/cs56-games-memory-card#27]
This was observed while using the cheat code to test functionality, but a score was displayed in the range of 300,000 which is not possible. Maybe look into why that occurred?

**Comment by xiaoheh** [comment]
This happens when you have paused for some time during the game. Already fixed

**Comment by mbahia** [comment]
Approved 50 pts
