### ISSUE TITLE
bug with the (2,1) grid

### ISSUE THREAD

**Issue by xiaoheh** [UCSB-CS56-Projects/cs56-games-memory-card#38]
A lot of times when we click on the (2,1) grid, the background color of that image would be very different from the original image. Some of the times it is normal. Need to look into the code and fix this problem

**Comment by xiaoheh** [comment]
Actually.. It seems the problem is that all images shown gray, while they should have been shown with white background. That is, the occasionally seen background color of grid (2,1) should be the correct color, and we need to set all buttons like that

**Comment by mbahia** [comment]
Approved 75 Pts
