### ISSUE TITLE
Label for level bug

### ISSUE THREAD

**Issue by ShaoyiZhang** [UCSB-CS56-Projects/cs56-games-memory-card#40]
The label for level on the right of the score label sometimes doesn't work correctly.

**Comment by ShaoyiZhang** [comment]
Estimated ~50

**Comment by mbahia** [comment]
Approved M.B.

**Comment by xiaoheh** [comment]
Wasn't able to reproduce the bug

**Comment by asyung** [comment]
closed because cannot reproduce bug
