### ISSUE TITLE
Reset button

### ISSUE THREAD

**Issue by asyung** [ucsb-cs56-projects/cs56-games-memory-card#49]
Hitting the reset button then cancel will start the timer. 

Also when you hit Menu -> Start/Resume -> Reset , multiple dialogs show up. 

300 Points

**Comment by asyung** [comment]
F16 OK (300 pts)

**Comment by seemantasaha** [comment]
W18 OK. 200 points.

**Comment by seemantasaha** [comment]
Fixed : Also when you hit Menu -> Start/Resume -> Reset , multiple dialogs show up.
Additionally this fixes the UI broken issue after clicking menu multiple times.
150 points.

**Comment by seemantasaha** [comment]
Resolved.
