### ISSUE TITLE
Recommended to refactor into MVC (Model View Controller) (DO FIRST!)

### ISSUE THREAD

**Issue by hyeminyoo** [ucsb-cs56-projects/cs56-games-memory-card#62]
Recommended refactor into MVC (Model View Controller) before tackling any other issues.
estimated: 500 points

**Comment by sean-shelton** [comment]
Estimated 300 points

**Comment by sean-shelton** [comment]
Estimated 300 points

**Comment by seemantasaha** [comment]
W18 OK. 400 points.
Points may be adjusted based on the effort needed to accomplish this task. (300-500)

**Comment by seemantasaha** [comment]
Closing this issue considering implementation of basic MVC pattern. There can be some cases where it does not strictly follow MVC pattern but the main motto of segregating view and data is accomplished.

**Comment by seemantasaha** [comment]
450 points considering effort required and fixing additional bugs.
