### ISSUE TITLE
Publish javadoc using the gh-pages workflow and remove javadoc from .gitignore

### ISSUE THREAD

**Issue by sean-shelton** [ucsb-cs56-projects/cs56-games-memory-card#65]
Currently, the project does not publish its javadoc online. This should be changed so that it follows the appropriate workflow as described [here](http://ucsb-cs56-pconrad.github.io/topics/javadoc_publishing_to_github_pages_from_private_repo/)

Estimated 100 points

**Comment by seemantasaha** [comment]
W18 OK. 100 points.

**Comment by seemantasaha** [comment]
This task is completed.
